## Preprocessing

In [3]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ['EIN', 'NAME'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [5]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [8]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [9]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [10]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
class_counts = application_df['CLASSIFICATION'].value_counts().replace(app,"Other")
class_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [11]:
# You may find it helpful to look at CLASSIFICATION value counts >1
clean_class_type = class_counts.loc[class_counts > 1]
clean_class_type.head()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Name: count, dtype: int64

In [12]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
numer_dum = pd.get_dummies(application_df)
numer_dum.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [14]:
# Split our preprocessed data into our features and target arrays
X = numer_dum.drop(['IS_SUCCESSFUL'], axis=1)
y = numer_dum['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=58)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [51]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn_model = tf.keras.models.Sequential()

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu", input_dim=43))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=16, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_15"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_35 (Dense)            (None, 16)                704

 dense_36 (Dense)            (None, 16)                272

 dense_37 (Dense)            (None, 1)                 17

=================================================================
Total params: 993 (3.88 KB)
Trainable params: 993 (3.88 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [52]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5842 - accuracy: 0.7091
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5592 - accuracy: 0.7296
Epoch 3/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5552 - accuracy: 0.7295
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5533 - accuracy: 0.7311
Epoch 5/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5518 - accuracy: 0.7310
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5511 - accuracy: 0.7318
Epoch 7/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5502 - accuracy: 0.7329
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5495 - accuracy: 0.7327
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7311
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7336
Epoch 11/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5477 - accuracy: 0.7333
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5475 - accuracy: 0.7322
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5474 - accuracy: 0.7336
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7339
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5469 - accuracy: 0.7325
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7336
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7338
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7328
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7329
Epoch 20/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7346
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7329
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7341
Epoch 23/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5455 - accuracy: 0.7339
Epoch 24/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5451 - accuracy: 0.7347
Epoch 25/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5447 - accuracy: 0.7336
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7344
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7338
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7348
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7350
Epoch 30/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5440 - accuracy: 0.7351
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5442 - accuracy: 0.7334
Epoch 32/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7349
Epoch 33/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5440 - accuracy: 0.7341
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7345
Epoch 35/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5436 - accuracy: 0.7359
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5434 - accuracy: 0.7349
Epoch 37/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5434 - accuracy: 0.7343
Epoch 38/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7352
Epoch 39/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5430 - accuracy: 0.7352
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7358
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7347
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5429 - accuracy: 0.7364
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7351
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7354
Epoch 45/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5426 - accuracy: 0.7350
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7356
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5427 - accuracy: 0.7355
Epoch 48/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5428 - accuracy: 0.7345
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7360
Epoch 50/50
804/804 [==============================] - 1s 2ms/step - loss: 0.5422 - accuracy: 0.7359

In [54]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5549 - accuracy: 0.7266 - 482ms/epoch - 2ms/step
Loss: 0.5549344420433044, Accuracy: 0.7266472578048706

In [57]:
# Export our model to HDF5 file
from tensorflow.keras.models import load_model
nn_model.save('/content/h5Files/AlphabetSoupCharity.hdf5')